### ISSUE TITLE
Displace structure along multiple vibrational modes

### ISSUE THREAD

**Issue by similt** [bobbypaton/pyQRC#3]
This code is awesome for displacing molecules along a particular vibrational mode. 
Is it possible to get a structure which is a linear combination of multiple vibrational modes?

**Comment by bobbypaton** [comment]
Currently, if there are multiple imaginary frequencies then the --auto option will result in a structure that is displaced along a linear combination of all of the imaginary normal modes. 

Currently this doesn't work with combining real frequencies rather than imaginary, and there is no control over the linear coefficients. Would that be useful?

**Comment by similt** [comment]
Thank you for reply. I am trying to generate a structure which is liner combinations of real frequencies.
